
-- Poistaa taulut tietokannasta
DROP TABLE IF EXISTS Invitations CASCADE;
DROP TABLE IF EXISTS Requests CASCADE;
DROP TABLE IF EXISTS Memberships CASCADE;
DROP TABLE IF EXISTS Communities CASCADE;
DROP TABLE IF EXISTS Bets CASCADE;
DROP TABLE IF EXISTS Goals CASCADE;
DROP TABLE IF EXISTS Matches CASCADE; 
DROP TABLE IF EXISTS Stadiums CASCADE;
DROP TABLE IF EXISTS Stages CASCADE;
DROP TABLE IF EXISTS Players CASCADE; 
DROP TABLE IF EXISTS Teams CASCADE;
DROP TABLE IF EXISTS Groups CASCADE;
DROP TABLE IF EXISTS Users CASCADE;